### ISSUE TITLE
Move Plan Domain Classes to OpenSRP Plan evalautor

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-plan-evaluator#10]
- [ ] Move Plan Domain Classes to OpenSRP Plan evaluator.

- [ ] This make it easier to have access to the domain object in both server and client while also exposing passing plan objects to the Evaluator

- [ ] Move task domain class to OpenSRP Plan evaluator.

**Comment by rehammuzzamil** [comment]
**Update:** 
Also, move Task Domain class to OpenSRP plan evaluator.
cc: @githengi
