### ISSUE TITLE
Add LOCATION_STOCK resource type

### ISSUE THREAD

**Issue by bennsimon** [opensrp/opensrp-plan-evaluator#127]
There is a requirement for eusm project that no tasks should be generated for structures with no stock. 

For this we can add a custom resource type `LOCATION_STOCK` which will bundle location data together will all the stock attached to it so that a condition on the plan definition can be set that checks whether the location has stock or not.

**Comment by mberg** [comment]
hi @bennsimon can you elaborate a bit on how this will work.  Is this a tag on the facility based on tasked assigned to it?  How would this be updated?  Please elaborate a bit more on this solution would work.

**Comment by bennsimon** [comment]
@mberg Its a tag that will apply on the facility when its being fetched by the plan evaluator. Facilities need stock so that product tasks are generated against it. The condition will then come in to check if the location has stocks assigned to it. If it has stock then both product and non-product tasks will be generated else task generation will be skipped for the facility.
