### ISSUE TITLE
Implement converter classes for OpenSRP domains to FHIR resources

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-plan-evaluator#16]
- [ ] Implement converter classes for OpenSRP domains to FHIR resources for the below Entities

- [ ] Client to Patient Resource
- [ ] Event to Encounter Resource
- [ ] Location to Location Resource
- [ ] Task to task resource

@rehammuzzamil you may have to move the domain classes for event and Client to the plan-evaluator -repo

**Comment by githengi** [comment]
@rehammuzzamil take note to move the domain tests on this PR https://github.com/OpenSRP/opensrp-server-core/pull/232#issuecomment-643432656

**Comment by rehammuzzamil** [comment]
Divided issue in two parts:
1- Move domain classes to opensrp-plan-evaluator library and removing from opensrp-server-core.
2- Implement converter classes from domain class to FIHR resource in opensrp-plan-evaluator library.
